apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotifyutils
  namespace: tedy
  labels:
    app: spotifyutils
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spotifyutils
  template:
    metadata:
      labels:
        app: spotifyutils
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: spotifyutils
          args:
            - "-RedirectURL=https://spotify.stoicatedy.ovh/auth"
          resources:
            limits:
              cpu: "200m"
              memory: "300M"
            requests:
              cpu: "200m"
              memory: "300M"
          image: ghcr.io/tedyst/spotifyutils:latest
          ports:
            - containerPort: 5000
            - containerPort: 5001
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: spotifyutils-secret
                  key: SECRETKEY
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spotifyutils-secret
                  key: SPOTIFYCLIENTID
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spotifyutils-secret
                  key: SPOTIFYCLIENTSECRET
            - name: GENIUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: spotifyutils-secret
                  key: GENIUSTOKEN
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: spotifyutils-secret
                  key: DATABASE
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: arm
