apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seafile.fullname" . }}
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "seafile.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "seafile.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "seafile.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          tty: true
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: 'DB_HOST'
              value: "{{ include "seafile.fullname" . }}-{{ .Values.database.nameOverride }}"
            - name: 'SEAFILE_SERVER_HOSTNAME'
              value: "{{ .Values.ingress.host }}"
            - name: 'DB_ROOT_PASSWD'
              value: "{{ .Values.database.mysql.password }}"
            - name: 'DB_PASSWORD'
              value: "{{ .Values.database.mysql.password }}"
            - name: 'DB_USERNAME'
              value: "root"
            {{ if .Values.envVariables }}
              {{- toYaml .Values.envVariables | nindent 12 }}
            {{ end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or (or .Values.persistentVolumeClaim.existingClaim .Values.persistentVolumeClaim.hostPort) .Values.persistentVolumeClaim.enable }}
          volumeMounts:
            - name: data
              mountPath: /shared
          {{- end }}
      {{- if or (or .Values.persistentVolumeClaim.existingClaim .Values.persistentVolumeClaim.hostPort) .Values.persistentVolumeClaim.enable }}
      volumes:
        - name: data
          {{- if .Values.persistentVolumeClaim.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.existingClaim }}
          {{- else if .Values.persistentVolumeClaim.hostPath }}
          hostPath:
            path: {{ .Values.persistentVolumeClaim.hostPath }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "seafile.serviceAccountName" . }}
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
