apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jellyfin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jellyfin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            {{- if .Values.envVariables }}
            {{- toYaml .Values.envVariables | nindent 12 }}
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
            {{- if .Values.jellyfin.enableDLNA }}
            - containerPort: 1900
              hostPort: 1900
              protocol: UDP
            {{- end}}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or (or .Values.persistentVolumeClaim.existingClaim .Values.persistentVolumeClaim.hostPort) (or .Values.persistentVolumeClaim.enable .Values.content.hostPath) }}
          volumeMounts:
          {{- if or (or .Values.persistentVolumeClaim.existingClaim .Values.persistentVolumeClaim.hostPort) .Values.persistentVolumeClaim.enable }}
            - name: data
              mountPath: /config
          {{- end }}
          {{- if .Values.content.hostPath }}
            - name: content
              mountPath: /content
          {{- end }}
          {{- end }}
      {{- if or (or .Values.persistentVolumeClaim.existingClaim .Values.persistentVolumeClaim.hostPort) (or .Values.persistentVolumeClaim.enable .Values.content.hostPath) }}
      volumes:
        {{- if or (or .Values.persistentVolumeClaim.existingClaim .Values.persistentVolumeClaim.hostPort) .Values.persistentVolumeClaim.enable  }}
        - name: data
          {{- if .Values.persistentVolumeClaim.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.existingClaim }}
          {{- else if .Values.persistentVolumeClaim.hostPath }}
          hostPath:
            path: {{ .Values.persistentVolumeClaim.hostPath }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "<CHARTNAME>.serviceAccountName" . }}
          {{- end }}
        {{- end }}
        {{- if .Values.content.hostPath }}
        - name: content
          hostPath:
            path: {{ .Values.content.hostPath }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
