{{- if not .Values.persistentVolumeClaim.existingClaim -}}
{{- if not .Values.persistentVolumeClaim.hostPort -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "jellyfin.fullname" . }}
  {{ if .Values.persistentVolumeClaim.keepOnDelete }}
  annotations:
    "helm.sh/resource-policy": "keep"
  {{- end }}
spec:
  {{- with .Values.persistentVolumeClaim.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
{{- end }}
{{- end }}