kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: email-simplelogin
  name: email-simplelogin
  namespace: email
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      k8s-app: email-simplelogin
  template:
    metadata:
      labels:
        k8s-app: email-simplelogin
    spec:
      terminationGracePeriodSeconds: 2
      initContainers:
        - name: simplelogin-migrate
          image: simplelogin/app:3.4.0
          command: ["flask"]
          args: ["db", "upgrade"]
          env:
            - name: LOCAL_FILE_UPLOAD
              value: "1"
            - name: ALIAS_DOMAINS
              value: '["stoicatedy.ovh"]'
            - name: URL
              value: "https://mail.stoicatedy.ovh"
            - name: SUPPORT_EMAIL
              value: "support@stoicatedy.ovh"
            - name: EMAIL_DOMAIN
              value: "stoicatedy.ovh"
            - name: EMAIL_SERVERS_WITH_PRIORITY
              value: '[(10, "stoicatedy.ovh.")]'
            - name: DISABLE_ALIAS_SUFFIX
              value: "1"
            - name: DISABLE_REGISTRATION
              value: "1"
            - name: DKIM_PRIVATE_KEY_PATH
              value: "/secret/private.key"
            - name: DKIM_PUBLIC_KEY_PATH
              value: "/secret/public.key"
            - name: DB_URI
              value: "postgresql://myuser:mypassword@email-db:5432/simplelogin"
            - name: FLASK_SECRET
              valueFrom:
                secretKeyRef:
                  key: flask-secret
                  name: email-simplelogin
          volumeMounts:
            - name: data
              mountPath: /secret
            - name: email-data
              mountPath: /code/static/upload
      containers:
        - name: simplelogin
          image: simplelogin/app:3.4.0
          ports:
            - containerPort: 7777
              protocol: TCP
          env:
            - name: LOCAL_FILE_UPLOAD
              value: "1"
            - name: ALIAS_DOMAINS
              value: '["stoicatedy.ovh"]'
            - name: URL
              value: "https://mail.stoicatedy.ovh"
            - name: SUPPORT_EMAIL
              value: "support@stoicatedy.ovh"
            - name: FLASK_ENV
              value: "production"
            - name: EMAIL_DOMAIN
              value: "stoicatedy.ovh"
            - name: EMAIL_SERVERS_WITH_PRIORITY
              value: '[(10, "stoicatedy.ovh.")]'
            - name: POSTFIX_SERVER
              value: "email-postfix"
            - name: DISABLE_ALIAS_SUFFIX
              value: "1"
            # - name: DISABLE_REGISTRATION
            #   value: "1"
            - name: DKIM_PRIVATE_KEY_PATH
              value: "/secret/private.key"
            - name: DKIM_PUBLIC_KEY_PATH
              value: "/secret/public.key"
            - name: GITHUB_CLIENT_ID
              value: "daed64612a783fdeef0a"
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: github-secret
                  name: email-simplelogin
            - name: GOOGLE_CLIENT_ID
              value: "585031273128-abbrsk4oujgee2q91d4op0obc72o43on.apps.googleusercontent.com"
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: google-secret
                  name: email-simplelogin
            - name: DB_URI
              value: "postgresql://myuser:mypassword@email-db:5432/simplelogin"
            - name: FLASK_SECRET
              valueFrom:
                secretKeyRef:
                  key: flask-secret
                  name: email-simplelogin
          volumeMounts:
            - name: data
              mountPath: /secret
            - name: email-data
              mountPath: /code/static/upload
      volumes:
        - name: data
          secret:
            secretName: email-simplelogin
        - name: email-data
          persistentVolumeClaim:
            claimName: email-simplelogin
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: arm
