apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: email-ingress
  namespace: email
spec:
  tls:
    - secretName: certificate-stoicatedy-ovh
  rules:
    - host: "mail.stoicatedy.ovh"
      http:
        paths:
          - path: /
            backend:
              serviceName: email-simplelogin
              servicePort: 7777
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-stoicatedy-ovh
  namespace: email
spec:
  secretName: certificate-stoicatedy-ovh
  commonName: stoicatedy.ovh
  usages:
    - server auth
    - client auth
    - digital signature
    - any
  dnsNames:
    - "stoicatedy.ovh"
    - "*.stoicatedy.ovh"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
