kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: email-db
  namespace: email
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: email-simplelogin
  namespace: email
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
