apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ctf-web
  namespace: tedy
spec:
  tls:
    - secretName: certificate-stoicatedy-ovh
  rules:
    - host: ctf.stoicatedy.ovh
      http:
        paths:
          - path: /
            backend:
              serviceName: ctf-web
              servicePort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ctf-shell
  namespace: tedy
spec:
  tls:
    - secretName: certificate-stoicatedy-ovh
  rules:
    - host: ctf-shell.stoicatedy.ovh
      http:
        paths:
          - path: /
            backend:
              serviceName: ctf-shell
              servicePort: 80
