apiVersion: v1
kind: Service
metadata:
  name: ctf-web
  namespace: tedy
spec:
  ports:
    - protocol: TCP
      port: 80
      name: "http"
      targetPort: 80
---
kind: Endpoints
apiVersion: v1
metadata:
  name: ctf-web
  namespace: tedy
subsets:
  - addresses:
      - ip: 192.168.10.4
    ports:
      - port: 80
        name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: ctf-shell
  namespace: tedy
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: "http"
    - protocol: TCP
      port: 22
      name: "ssh"
      targetPort: 22
---
kind: Endpoints
apiVersion: v1
metadata:
  name: ctf-shell
  namespace: tedy
subsets:
  - addresses:
      - ip: 192.168.10.3
    ports:
      - port: 80
        name: "http"
      - port: 22
        name: "ssh"
