apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keel-ingress
  namespace: kube-system
spec:
  routes:
    - match: Host(`keel.stoicatedy.ovh`)
      kind: Rule
      services:
        - name: keel
          port: 9300
  middlewares:
    - name: hsts-header
  tls:
    secretName: certificate-stoicatedy-ovh
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-stoicatedy-ovh
  namespace: kube-system
spec:
  secretName: certificate-stoicatedy-ovh
  commonName: stoicatedy.ovh
  usages:
    - server auth
    - client auth
    - digital signature
    - any
  dnsNames:
    - "stoicatedy.ovh"
    - "*.stoicatedy.ovh"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
