apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: prometheus
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:9090
    - job_name: hypixel
      honor_timestamps: true
      scrape_interval: 60s
      scrape_timeout: 5s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - hypixelmonitor.tedy:8000
    - job_name: openvpn
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - openvpn-exporter.tedy:9176
    - job_name: spotifyutils
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - spotifyutils-metrics.tedy:5001
    - job_name: tati-dekstop
      honor_timestamps: true
      scrape_interval: 10s
      scrape_timeout: 3s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - 192.168.10.54:9182
    - job_name: 'node-exporter'
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: 'node-exporter'
        action: keep
