# Default values for spotifyutils.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/tedyst/spotifyutils
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: "chart-example.local"
  tls:
    []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

livenessProbe:
  {}
  # httpGet:
  #   path: /
  #   port: http
readinessProbe:
  httpGet:
    path: /
    port: http

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

spotifyutils:
  # -- Enable Debug mode
  debug: false
  # -- Enable Metrics
  metrics: false
  # -- Base URL to Redirect to
  redirectURL: "http://spotify.cluster/auth"
  # -- Token from Genius
  geniusToken: ""
  # -- Secret key generated from `openssl rand -hex 16`
  secretKey: ""
  # -- Client ID from Spotify
  spotifyClientID: ""
  # -- Client Secret from Spotify
  spotifyClientSecret: ""

database:
  # -- Choose whether to create another mysql database
  create: true
  nameOverride: "database"
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
  # -- If creating a DB, what should be the size of the PersistentVolumeClaim
  persistentVolumeClaim:
    size: 300Mi
    accessModes:
      - ReadWriteOnce
  service:
    # -- The MySQL port
    port: 3306
  # -- The MySQL address, without port
  address: "db"
  mysql:
    # -- The MySQL user
    user: "root"
    # -- The MySQL password
    password: "password"
    # -- The MySQL database
    database: "spotifyutils"
