# Default values for spotifyutils.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/tedyst/spotifyutils
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  traefik: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: "chart-example.local"
  tls:
    {}
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

livenessProbe:
  {}
  # httpGet:
  #   path: /
  #   port: http
readinessProbe:
  {}
  # httpGet:
  #   path: /
  #   port: http

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

spotifyutils:
  debug: false
  metrics: false
  redirectURL: "http://spotify.cluster/auth"
  geniusToken: ""
  secretKey: ""
  spotifyClientID: ""
  spotifyClientSecret: ""

database:
  user: "root"
  password: "password"
  address: "db"
  port: "3306"
  database: "spotifyutils"
