{
 "title": "Hypixel",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Users Tracked",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(hypixel_exp)" }
   ]
  },
  {
   "title": "Bedwars Win Streak",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hypixel_bedwars_win_streak", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Biggest Flex Ever",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hypixel_skywars_souls", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "SkyWars Win Streak",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hypixel_skywars_win_streak", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Bedwars XP Increase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hypixel_bedwars_exp[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Hypixel XP Increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(hypixel_exp[1m])", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Karma",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hypixel_karma", "legendFormat": "{{name}}" }
   ]
  }
 ]
}