kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
  namespace: filme
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: radarr
  template:
    metadata:
      labels:
        k8s-app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          ports:
            - containerPort: 7878
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /mnt/hddext4/
              name: hdd
          resources:
            limits:
              memory: "500Mi"
              cpu: "1000m"
      volumes:
        - name: hdd
          hostPath:
            path: /mnt/hddext4/Jellyfin-all/
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: tedy-desktop
