{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.traefik -}}
{{- $fullName := include "spotifyutils.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "spotifyutils.fullname" . }}
  labels:
  {{- include "spotifyutils.labels" . | nindent 4 }}
spec:
  routes:
    - match: "Host(`{{ .Values.ingress.host }}`)"
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
  tls:
    {{ toYaml .Values.ingress.tls | nindent 4 }}
{{- end }}
{{- end }}