{{- $fullName := include "spotifyutils.fullname" . -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "spotifyutils.fullname" . }}
data:
  GENIUSTOKEN: {{ required "You need to specify a Genius Token" .Values.spotifyutils.geniusToken | b64enc | quote }}
  SECRETKEY: {{ required "You need to specify a Secret Key" .Values.spotifyutils.secretKey | b64enc | quote }}
  SPOTIFYCLIENTID: {{ required "You need to specify a Spotify Client ID" .Values.spotifyutils.spotifyClientID | b64enc | quote }}
  SPOTIFYCLIENTSECRET: {{ required "You need to specify a Spotify Client Secret" .Values.spotifyutils.spotifyClientSecret | b64enc | quote}}
  DATABASE: {{ include "spotifyutils.database.uri" . | b64enc | quote }}
