{{- $fullName := include "cloudflare-docker-updater.fullname" . -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $fullName }}
data:
  CFZONEID: {{ required "You need to specify a Zone ID" .Values.updater.zoneID | b64enc | quote }}
  CFUSERID: {{ required "You need to specify a User ID" .Values.updater.userID | b64enc | quote }}
  CFTOKEN: {{ required "You need to specify a CF Token" .Values.updater.token | b64enc | quote }}
  CFHOST: {{ required "You need to specify the hosts" .Values.updater.host | b64enc | quote }}
