{{- $fullName := include "mariadb.fullname" . -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $fullName }}
data:
  MYSQLPASSWORD: {{ required "You need to specify a Database Password" .Values.mysql.password | b64enc | quote }}
