apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testing
  namespace: tedy
spec:
  tls:
    - secretName: certificate-stoicatedy-ovh
  rules:
    - host: "testing.stoicatedy.ovh"
      http:
        paths:
          - path: /
            backend:
              serviceName: testing
              servicePort: 80
