apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: tedy
  labels:
    app: cloudflare
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: cloudflare
          resources:
            limits:
              cpu: "10m"
              memory: "10M"
          image: tedyst/cloudflare-docker-updater:latest
          env:
            - name: CFZONEID
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: CFZONEID
            - name: CFUSERID
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: CFUSERID
            - name: CFTOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: CFTOKEN
            - name: CFHOST
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: CFHOST
            - name: CFINTERVAL
              value: "3600"
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: arm