{{- $fullName := include "bitwarden-rs.fullname" . -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $fullName }}
data:
  {{- if .Values.bitwarden.hibpKey }}
  HIBPKEY: {{ .Values.bitwarden.hibpKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.bitwarden.smtp.password }}
  SMTPPASSWORD: {{ .Values.bitwarden.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.bitwarden.yubico.secretKey }}
  YUBICOSECRETKEY: {{ .Values.bitwarden.yubico.secretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.bitwarden.yubico.clientID }}
  YUBICOCLIENTID: {{ .Values.bitwarden.yubico.clientID | b64enc | quote }}
  {{- end }}
  {{- if .Values.bitwarden.admin.token }}
  ADMINTOKEN: {{ .Values.bitwarden.admin.token | b64enc | quote }}
  {{- end }}
