apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: filme
  labels:
    app: jellyfin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      containers:
        - name: jellyfin
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: "500m"
              memory: "300M"
          image: linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 1900
              hostPort: 1900
              protocol: UDP
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: hdd
              mountPath: /mnt/hddext4/
          securityContext:
            privileged: true
      volumes:
        - name: config-volume
          hostPath:
            path: /mnt/hddext4/jellyfin/config
        - name: hdd
          hostPath:
            path: /mnt/hddext4/Jellyfin-all/
        - name: videocard
          hostPath:
            path: /dev/dri
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: tedy-desktop
