apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jellyfin
  namespace: filme
spec:
  tls:
    - secretName: "certificate-stoicatedy-ovh"
  rules:
    - host: jellyfin.stoicatedy.ovh
      http:
        paths:
          - path: /
            backend:
              serviceName: jellyfin-service
              servicePort: 8096
