apiVersion: v2
appVersion: 7.1.5
description: A Helm chart for Kubernetes
name: seafile
type: application
version: 0.1.0

dependencies:
  - name: mariadb
    version: 0.1.3
    repository: file://../mariadb
    condition: database.create
    alias: database

maintainers:
  - name: Stoica Tedy
    email: stoicatedy@gmail.com
    url: https://stoicatedy.ovh
