{
 "title": "Hypixel",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Users",
    "query": "label_values(hypixel_networkExp, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Users Tracked",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(hypixel_networkExp)" }
   ]
  },
  {
   "title": "Bedwars Win Streak",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hypixel_Bedwars_winstreak{name=~\"$group\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Biggest Flex Ever",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hypixel_SkyWars_souls{name=~\"$group\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "SkyWars Win Streak",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hypixel_SkyWars_win_streak{name=~\"$group\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "XP Increase",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hypixel_networkExp{name=~\"$group\"}[$__range])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bedwars XP Increase",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hypixel_Bedwars_Experience{name=~\"$group\"}[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Hypixel XP Increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hypixel_networkExp{name=~\"$group\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Karma",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hypixel_karma{name=~\"$group\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ranked Games",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(hypixel_SkyWars_games_ranked{name=~\"$group\"}[$__range])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "SkyBlock Balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hypixel_skyblock_balance{profile=\"737984c653a944df8a71c049618c92b6\", name=\"Tedyst\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Combat XP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hypixel_skyblock_skill_combat{profile=\"737984c653a944df8a71c049618c92b6\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Combat XP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hypixel_skyblock_skill_combat{profile=\"737984c653a944df8a71c049618c92b6\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}