{
 "title": "Spotify Utils",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m" },
   { "name": "job", "query": "spotifyutils" }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "spotifyutils_users{app=\"spotifyutils\"}"
    }
   ]
  },
  {
   "title": "Track Informations Searched",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(spotifyutils_track_information_searched{app=\"spotifyutils\"}[$interval]))",
     "legendFormat": "Track Information"
    },
    {
     "expr": "sum(increase(spotifyutils_track_lyrics_searched{app=\"spotifyutils\"}[$interval]))",
     "legendFormat": "Lyrics"
    }
   ]
  },
  {
   "title": "Log Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(log_messages{app=\"spotifyutils\", level=\"warning\"}[$interval]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(increase(log_messages{app=\"spotifyutils\", level=\"info\"}[$interval]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(increase(log_messages{app=\"spotifyutils\", level=\"error\"}[$interval]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Recent Tracks Added",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(spotifyutils_recent_tracks_added{app=\"spotifyutils\"}[2m]))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"spotifyutils\"}",
     "legendFormat": "resident {{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{app=\"spotifyutils\"}",
     "legendFormat": "virtual {{instance}}"
    }
   ]
  },
  {
   "title": "Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app=\"spotifyutils\"}",
     "legendFormat": "bytes allocated {{instance}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app=\"spotifyutils\"}[30s])",
     "legendFormat": "alloc rate {{instance}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{app=\"spotifyutils\"}",
     "legendFormat": "stack inuse {{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{app=\"spotifyutils\"}",
     "legendFormat": "heap inuse {{instance}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(spotifyutils_request_duration_seconds_bucket{app=\"spotifyutils\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (route) (increase(spotifyutils_request_duration_seconds_bucket{le=\"+Inf\", status_code=\"200\", app=\"spotifyutils\"}[30s]))",
     "legendFormat": "Success {{route}}"
    },
    {
     "expr": "sum by (route) (increase(spotifyutils_request_duration_seconds_bucket{le=\"+Inf\", status_code!=\"200\", status_code!=\"302\", status_code!=\"304\", status_code!=\"301\", app=\"spotifyutils\"}[30s]))",
     "legendFormat": "Fail {{route}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app=\"spotifyutils\"}",
     "legendFormat": "Count {{instance}}"
    }
   ]
  },
  {
   "title": "Memstats Deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{app=\"spotifyutils\"}[$interval])",
     "legendFormat": "bytes allocated {{instance}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app=\"spotifyutils\"}[$interval])",
     "legendFormat": "alloc rate {{instance}}"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{app=\"spotifyutils\"}[$interval])",
     "legendFormat": "stack inuse {{instance}}"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{app=\"spotifyutils\"}[$interval])",
     "legendFormat": "heap inuse {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{app=\"spotifyutils\"}[$interval])",
     "legendFormat": "resident {{instance}}"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{app=\"spotifyutils\"}[$interval])",
     "legendFormat": "virtual {{instance}}"
    }
   ]
  }
 ]
}