name: Build Helm Charts

on:
  push:
    branches:
      - master
      - helm

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run Build
        run: |
          cd charts/
          helm repo add tedy https://helm.stoicatedy.ovh
          helm repo update
          for d in */ ; do
            helm dependency build $d
            helm package $d
          done
          mkdir /tmp/action
          git checkout gh-pages
          mv *.tgz ../
          cd ../
          helm repo index .
          git add .
          git commit . -m "Automated Build"
          git push
